// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lbrictson/cogs/ent/notificationchannel"
	"github.com/lbrictson/cogs/ent/schema"
)

// NotificationChannel is the model entity for the NotificationChannel schema.
type NotificationChannel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// SlackConfig holds the value of the "slack_config" field.
	SlackConfig schema.SlackConfig `json:"slack_config,omitempty"`
	// EmailConfig holds the value of the "email_config" field.
	EmailConfig schema.EmailConfig `json:"email_config,omitempty"`
	// WebhookConfig holds the value of the "webhook_config" field.
	WebhookConfig schema.WebhookConfig `json:"webhook_config,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationChannel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationchannel.FieldSlackConfig, notificationchannel.FieldEmailConfig, notificationchannel.FieldWebhookConfig:
			values[i] = new([]byte)
		case notificationchannel.FieldEnabled:
			values[i] = new(sql.NullBool)
		case notificationchannel.FieldID:
			values[i] = new(sql.NullInt64)
		case notificationchannel.FieldName, notificationchannel.FieldType:
			values[i] = new(sql.NullString)
		case notificationchannel.FieldCreatedAt, notificationchannel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationChannel fields.
func (nc *NotificationChannel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationchannel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			nc.ID = int(value.Int64)
		case notificationchannel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				nc.CreatedAt = value.Time
			}
		case notificationchannel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				nc.UpdatedAt = value.Time
			}
		case notificationchannel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				nc.Name = value.String
			}
		case notificationchannel.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				nc.Type = value.String
			}
		case notificationchannel.FieldSlackConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field slack_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &nc.SlackConfig); err != nil {
					return fmt.Errorf("unmarshal field slack_config: %w", err)
				}
			}
		case notificationchannel.FieldEmailConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field email_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &nc.EmailConfig); err != nil {
					return fmt.Errorf("unmarshal field email_config: %w", err)
				}
			}
		case notificationchannel.FieldWebhookConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field webhook_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &nc.WebhookConfig); err != nil {
					return fmt.Errorf("unmarshal field webhook_config: %w", err)
				}
			}
		case notificationchannel.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				nc.Enabled = value.Bool
			}
		default:
			nc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationChannel.
// This includes values selected through modifiers, order, etc.
func (nc *NotificationChannel) Value(name string) (ent.Value, error) {
	return nc.selectValues.Get(name)
}

// Update returns a builder for updating this NotificationChannel.
// Note that you need to call NotificationChannel.Unwrap() before calling this method if this NotificationChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (nc *NotificationChannel) Update() *NotificationChannelUpdateOne {
	return NewNotificationChannelClient(nc.config).UpdateOne(nc)
}

// Unwrap unwraps the NotificationChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (nc *NotificationChannel) Unwrap() *NotificationChannel {
	_tx, ok := nc.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationChannel is not a transactional entity")
	}
	nc.config.driver = _tx.drv
	return nc
}

// String implements the fmt.Stringer.
func (nc *NotificationChannel) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationChannel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", nc.ID))
	builder.WriteString("created_at=")
	builder.WriteString(nc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(nc.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(nc.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(nc.Type)
	builder.WriteString(", ")
	builder.WriteString("slack_config=")
	builder.WriteString(fmt.Sprintf("%v", nc.SlackConfig))
	builder.WriteString(", ")
	builder.WriteString("email_config=")
	builder.WriteString(fmt.Sprintf("%v", nc.EmailConfig))
	builder.WriteString(", ")
	builder.WriteString("webhook_config=")
	builder.WriteString(fmt.Sprintf("%v", nc.WebhookConfig))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", nc.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationChannels is a parsable slice of NotificationChannel.
type NotificationChannels []*NotificationChannel
