// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/cogs/ent/notificationchannel"
	"github.com/lbrictson/cogs/ent/predicate"
)

// NotificationChannelQuery is the builder for querying NotificationChannel entities.
type NotificationChannelQuery struct {
	config
	ctx        *QueryContext
	order      []notificationchannel.OrderOption
	inters     []Interceptor
	predicates []predicate.NotificationChannel
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NotificationChannelQuery builder.
func (ncq *NotificationChannelQuery) Where(ps ...predicate.NotificationChannel) *NotificationChannelQuery {
	ncq.predicates = append(ncq.predicates, ps...)
	return ncq
}

// Limit the number of records to be returned by this query.
func (ncq *NotificationChannelQuery) Limit(limit int) *NotificationChannelQuery {
	ncq.ctx.Limit = &limit
	return ncq
}

// Offset to start from.
func (ncq *NotificationChannelQuery) Offset(offset int) *NotificationChannelQuery {
	ncq.ctx.Offset = &offset
	return ncq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ncq *NotificationChannelQuery) Unique(unique bool) *NotificationChannelQuery {
	ncq.ctx.Unique = &unique
	return ncq
}

// Order specifies how the records should be ordered.
func (ncq *NotificationChannelQuery) Order(o ...notificationchannel.OrderOption) *NotificationChannelQuery {
	ncq.order = append(ncq.order, o...)
	return ncq
}

// First returns the first NotificationChannel entity from the query.
// Returns a *NotFoundError when no NotificationChannel was found.
func (ncq *NotificationChannelQuery) First(ctx context.Context) (*NotificationChannel, error) {
	nodes, err := ncq.Limit(1).All(setContextOp(ctx, ncq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{notificationchannel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ncq *NotificationChannelQuery) FirstX(ctx context.Context) *NotificationChannel {
	node, err := ncq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NotificationChannel ID from the query.
// Returns a *NotFoundError when no NotificationChannel ID was found.
func (ncq *NotificationChannelQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ncq.Limit(1).IDs(setContextOp(ctx, ncq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{notificationchannel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ncq *NotificationChannelQuery) FirstIDX(ctx context.Context) int {
	id, err := ncq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NotificationChannel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NotificationChannel entity is found.
// Returns a *NotFoundError when no NotificationChannel entities are found.
func (ncq *NotificationChannelQuery) Only(ctx context.Context) (*NotificationChannel, error) {
	nodes, err := ncq.Limit(2).All(setContextOp(ctx, ncq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{notificationchannel.Label}
	default:
		return nil, &NotSingularError{notificationchannel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ncq *NotificationChannelQuery) OnlyX(ctx context.Context) *NotificationChannel {
	node, err := ncq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NotificationChannel ID in the query.
// Returns a *NotSingularError when more than one NotificationChannel ID is found.
// Returns a *NotFoundError when no entities are found.
func (ncq *NotificationChannelQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ncq.Limit(2).IDs(setContextOp(ctx, ncq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{notificationchannel.Label}
	default:
		err = &NotSingularError{notificationchannel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ncq *NotificationChannelQuery) OnlyIDX(ctx context.Context) int {
	id, err := ncq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NotificationChannels.
func (ncq *NotificationChannelQuery) All(ctx context.Context) ([]*NotificationChannel, error) {
	ctx = setContextOp(ctx, ncq.ctx, "All")
	if err := ncq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NotificationChannel, *NotificationChannelQuery]()
	return withInterceptors[[]*NotificationChannel](ctx, ncq, qr, ncq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ncq *NotificationChannelQuery) AllX(ctx context.Context) []*NotificationChannel {
	nodes, err := ncq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NotificationChannel IDs.
func (ncq *NotificationChannelQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ncq.ctx.Unique == nil && ncq.path != nil {
		ncq.Unique(true)
	}
	ctx = setContextOp(ctx, ncq.ctx, "IDs")
	if err = ncq.Select(notificationchannel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ncq *NotificationChannelQuery) IDsX(ctx context.Context) []int {
	ids, err := ncq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ncq *NotificationChannelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ncq.ctx, "Count")
	if err := ncq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ncq, querierCount[*NotificationChannelQuery](), ncq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ncq *NotificationChannelQuery) CountX(ctx context.Context) int {
	count, err := ncq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ncq *NotificationChannelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ncq.ctx, "Exist")
	switch _, err := ncq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ncq *NotificationChannelQuery) ExistX(ctx context.Context) bool {
	exist, err := ncq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NotificationChannelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ncq *NotificationChannelQuery) Clone() *NotificationChannelQuery {
	if ncq == nil {
		return nil
	}
	return &NotificationChannelQuery{
		config:     ncq.config,
		ctx:        ncq.ctx.Clone(),
		order:      append([]notificationchannel.OrderOption{}, ncq.order...),
		inters:     append([]Interceptor{}, ncq.inters...),
		predicates: append([]predicate.NotificationChannel{}, ncq.predicates...),
		// clone intermediate query.
		sql:  ncq.sql.Clone(),
		path: ncq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NotificationChannel.Query().
//		GroupBy(notificationchannel.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ncq *NotificationChannelQuery) GroupBy(field string, fields ...string) *NotificationChannelGroupBy {
	ncq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NotificationChannelGroupBy{build: ncq}
	grbuild.flds = &ncq.ctx.Fields
	grbuild.label = notificationchannel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.NotificationChannel.Query().
//		Select(notificationchannel.FieldCreatedAt).
//		Scan(ctx, &v)
func (ncq *NotificationChannelQuery) Select(fields ...string) *NotificationChannelSelect {
	ncq.ctx.Fields = append(ncq.ctx.Fields, fields...)
	sbuild := &NotificationChannelSelect{NotificationChannelQuery: ncq}
	sbuild.label = notificationchannel.Label
	sbuild.flds, sbuild.scan = &ncq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NotificationChannelSelect configured with the given aggregations.
func (ncq *NotificationChannelQuery) Aggregate(fns ...AggregateFunc) *NotificationChannelSelect {
	return ncq.Select().Aggregate(fns...)
}

func (ncq *NotificationChannelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ncq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ncq); err != nil {
				return err
			}
		}
	}
	for _, f := range ncq.ctx.Fields {
		if !notificationchannel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ncq.path != nil {
		prev, err := ncq.path(ctx)
		if err != nil {
			return err
		}
		ncq.sql = prev
	}
	return nil
}

func (ncq *NotificationChannelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NotificationChannel, error) {
	var (
		nodes = []*NotificationChannel{}
		_spec = ncq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NotificationChannel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NotificationChannel{config: ncq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ncq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ncq *NotificationChannelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ncq.querySpec()
	_spec.Node.Columns = ncq.ctx.Fields
	if len(ncq.ctx.Fields) > 0 {
		_spec.Unique = ncq.ctx.Unique != nil && *ncq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ncq.driver, _spec)
}

func (ncq *NotificationChannelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(notificationchannel.Table, notificationchannel.Columns, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt))
	_spec.From = ncq.sql
	if unique := ncq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ncq.path != nil {
		_spec.Unique = true
	}
	if fields := ncq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationchannel.FieldID)
		for i := range fields {
			if fields[i] != notificationchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ncq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ncq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ncq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ncq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ncq *NotificationChannelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ncq.driver.Dialect())
	t1 := builder.Table(notificationchannel.Table)
	columns := ncq.ctx.Fields
	if len(columns) == 0 {
		columns = notificationchannel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ncq.sql != nil {
		selector = ncq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ncq.ctx.Unique != nil && *ncq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ncq.predicates {
		p(selector)
	}
	for _, p := range ncq.order {
		p(selector)
	}
	if offset := ncq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ncq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NotificationChannelGroupBy is the group-by builder for NotificationChannel entities.
type NotificationChannelGroupBy struct {
	selector
	build *NotificationChannelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ncgb *NotificationChannelGroupBy) Aggregate(fns ...AggregateFunc) *NotificationChannelGroupBy {
	ncgb.fns = append(ncgb.fns, fns...)
	return ncgb
}

// Scan applies the selector query and scans the result into the given value.
func (ncgb *NotificationChannelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ncgb.build.ctx, "GroupBy")
	if err := ncgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotificationChannelQuery, *NotificationChannelGroupBy](ctx, ncgb.build, ncgb, ncgb.build.inters, v)
}

func (ncgb *NotificationChannelGroupBy) sqlScan(ctx context.Context, root *NotificationChannelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ncgb.fns))
	for _, fn := range ncgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ncgb.flds)+len(ncgb.fns))
		for _, f := range *ncgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ncgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ncgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NotificationChannelSelect is the builder for selecting fields of NotificationChannel entities.
type NotificationChannelSelect struct {
	*NotificationChannelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ncs *NotificationChannelSelect) Aggregate(fns ...AggregateFunc) *NotificationChannelSelect {
	ncs.fns = append(ncs.fns, fns...)
	return ncs
}

// Scan applies the selector query and scans the result into the given value.
func (ncs *NotificationChannelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ncs.ctx, "Select")
	if err := ncs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotificationChannelQuery, *NotificationChannelSelect](ctx, ncs.NotificationChannelQuery, ncs, ncs.inters, v)
}

func (ncs *NotificationChannelSelect) sqlScan(ctx context.Context, root *NotificationChannelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ncs.fns))
	for _, fn := range ncs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ncs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ncs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
