// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/cogs/ent/predicate"
	"github.com/lbrictson/cogs/ent/scriptstats"
)

// ScriptStatsDelete is the builder for deleting a ScriptStats entity.
type ScriptStatsDelete struct {
	config
	hooks    []Hook
	mutation *ScriptStatsMutation
}

// Where appends a list predicates to the ScriptStatsDelete builder.
func (ssd *ScriptStatsDelete) Where(ps ...predicate.ScriptStats) *ScriptStatsDelete {
	ssd.mutation.Where(ps...)
	return ssd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ssd *ScriptStatsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ssd.sqlExec, ssd.mutation, ssd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ssd *ScriptStatsDelete) ExecX(ctx context.Context) int {
	n, err := ssd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ssd *ScriptStatsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(scriptstats.Table, sqlgraph.NewFieldSpec(scriptstats.FieldID, field.TypeInt))
	if ps := ssd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ssd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ssd.mutation.done = true
	return affected, err
}

// ScriptStatsDeleteOne is the builder for deleting a single ScriptStats entity.
type ScriptStatsDeleteOne struct {
	ssd *ScriptStatsDelete
}

// Where appends a list predicates to the ScriptStatsDelete builder.
func (ssdo *ScriptStatsDeleteOne) Where(ps ...predicate.ScriptStats) *ScriptStatsDeleteOne {
	ssdo.ssd.mutation.Where(ps...)
	return ssdo
}

// Exec executes the deletion query.
func (ssdo *ScriptStatsDeleteOne) Exec(ctx context.Context) error {
	n, err := ssdo.ssd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{scriptstats.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ssdo *ScriptStatsDeleteOne) ExecX(ctx context.Context) {
	if err := ssdo.Exec(ctx); err != nil {
		panic(err)
	}
}
