// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Access is the predicate function for access builders.
type Access func(*sql.Selector)

// History is the predicate function for history builders.
type History func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Script is the predicate function for script builders.
type Script func(*sql.Selector)

// ScriptStats is the predicate function for scriptstats builders.
type ScriptStats func(*sql.Selector)

// Secret is the predicate function for secret builders.
type Secret func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
